local captions = {
        --"meat.growl",
        --"meat.growl_somber",
        --"meat.munch",

        --"narrator.christmas_complete",
        --"narrator.vinny_slept_soundly",
        --"narrator.asking_for_help",
        --"narrator.attic_intro",
        --"narrator.basement_intro",
        --"narrator.christmas_tree_leaves",
        --"narrator.didnt_need_to_try",
        --"narrator.fridge_locked",
        --"narrator.front_door_intro",
        --"narrator.fun_of_the_game",
        --"narrator.glass_different_to_mug",
        --"narrator.good_at_pachinko",
        --"narrator.meat_somber",
        --"narrator.meat_tendrils",
        --"narrator.no_one_watching",
        --"narrator.nothing_to_prove",
        --"narrator.objectives",
        --"narrator.outside_intro",
        --"narrator.pachinko_fail",
        --"narrator.pachinko_intro",
        --"narrator.pachinko_success",
        --"narrator.pull_the_lever_01",
        --"narrator.pull_the_lever_02",
        --"narrator.pull_the_lever_03",
        --"narrator.pull_the_lever_04",
        --"narrator.television",
        --"narrator.tree_felled_first",
        --"narrator.tree_felled_last",
        --"narrator.tree_intro",
        --"narrator.vinny_overslept",
        --"narrator.wrong_stream_title",
        --"phone.hang_up_click",
        --"phone.hang_up_loop",
        --"phone.ring_once",
        --"phone.ring_loop",
        --"phone.quip.hl1_breathe",
        --"phone.quip.gman_bissing",
        --"phone.quip.hatsune_miku",
        --"phone.quip.jerma_punched_car",
        --"phone.quip.jerma_realise_ugly",
        --"phone.quip.jerma_scream",
        --"phone.quip.limmy_vinny",
        --"phone.quip.mmm_monkey",
        --"phone.quip.music_industry_code",
        --"phone.quip.ass_is_heavy",
        --"phone.quip.ass_is_heavy!",
        --"phone.quip.ufo_porno",
        --"phone.quip.fart_meme",
        --"phone.quip.mario_haha",
        --"phone.quip.tommy_joker",
        --"phone.quip.f_you_luigi",
        --"phone.quip.grape_fruit",

        --"vinny.jerma_saw_candy_crush",
        --"vinny.jerma_saw_delivery_of_sharp",
        --"vinny.jerma_saw_delivery_of_sharp_reverb",
        --"vinny.jerma_saw_dont_do_that",
        --"vinny.jerma_saw_dont_need_to_see",
            --"vinny.jerma_saw_failed_attempts",
            "vinny.jerma_saw_failed_attempts_01",
            "vinny.jerma_saw_failed_attempts_02",
            "vinny.jerma_saw_failed_attempts_03",
        --"vinny.jerma_saw_friend_tied_up",
        --"vinny.jerma_saw_get_out_of_room",
        --"vinny.jerma_saw_giberish",
        --"vinny.jerma_saw_giberish_reverb",
        --"vinny.jerma_saw_glow_in_dark",
        --"vinny.jerma_saw_glow_in_dark_reverb",
        --"vinny.jerma_saw_good_at_making_games",
        --"vinny.jerma_saw_good_at_making_games_reverb",
        --"vinny.jerma_saw_gun_shoot_guy",
        --"vinny.jerma_saw_its_me_saw",
        --"vinny.jerma_saw_let_me_stop_you",
        --"vinny.jerma_saw_macular_degeneration",
        --"vinny.jerma_saw_made_your_choice",
        --"vinny.jerma_saw_made_your_choice_reverb",
        --"vinny.jerma_saw_no",
        --"vinny.jerma_saw_photo_of_me",
            --"vinny.jerma_saw_snowman",
            --"vinny.jerma_saw_snowman_01",
            --"vinny.jerma_saw_snowman_02",
        --"vinny.jerma_saw_sudoku",
        --"vinny.jerma_saw_this_guys_mad",
        --"vinny.jerma_saw_too_many_sweets",
        --"vinny.jerma_saw_too_many_sweets_reverb",
        --"vinny.jerma_saw_use_pair_of_hands",
        --"vinny.jerma_saw_use_pair_of_hands_reverb",
        --"vinny.jerma_saw_yes",
        --"vinny.jerma_saw_welcomemurder",
        --"vinny.jerma_saw_welcomemurder_reverb",
        --"vinny.jerma_saw_reallydisgusting",

        --"vinny.meat_thrown_food",
        --"vinny.gnome_vox",
        --"vinny.tree_fall",
        --"vinny.lightning_strike",
        --"vinny.clown_laugh",
        --"vinny.evil_laugh",
        --"vinny.heartbeat",
        --"vinny.wood_chop",
        --"vinny.scientist_vox",
        --"vinny.christmas_special",
        --"vinny.light_on_echo",
        --"vinny.player_captured",
        --"vinny.tv_turn_on",
        --"vinny.tv_turn_off",
        --"vinny.tv_hum_loop",
        --"vinny.rocket",
        --"vinny.holy_choir",
        --"vinny.rat_squeal",
        --"vinny.snark.deploy",
        --"vinny.snark.hunt",
        --"vinny.snark.blast",
        --"vinny.wall_grind_lp",
        --"vinny.multi_test",
        --"vinny.dirt_dig",
        --"vinny.christmas_toy_die",
        --"vinny.screee",
        --"vinny.screee_end",
        --"vinny.screee2",
        --"vinny.screee_hitch",
        --"vinny.higgs_breath",
        --"vinny.spoopy_skeleton",
        --"vinny.nedry_ah_ah_ah",
        --"vinny.reviver_run_loop",
        --"vinny.music.roll_up",
        --"vinny.music.roll_up_wind_down",
        --"vinny.music.morning_magic",
        --"vinny.music.deck_the_halls",
        --"vinny.null",
        --"vinny.vortigese09",
        --"vinny.scribble",
        --"vinny.speen",
        --"vinny.hohoho_04",
        --"vinny.hohoho_ominous",
        --"vinny.merry_christmas_santa",
        --"vinny.milk_pour",
        --"vinny.car_engine",
        --"vinny.flesh_burn",
        --"vinny.cat_meow",
        --"vinny.timer_tick_loop",
        --"vinny.tv_static",
        --"vinny.jerma_rats",
    }

local current = 0

function Next()
    current = current + 1
    if current > #captions then
        current = 1
    end

    EmitSoundOn(captions[current], Entities:GetLocalPlayer())
end

function Prev()
    current = current - 1
    if current < 1 then
        current = #captions
    end

    EmitSoundOn(captions[current], Entities:GetLocalPlayer())
end

function Same()
    EmitSoundOn(captions[current], Entities:GetLocalPlayer())
end